url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gemma McCarley" # the name of your site, e.g. ACME Corp.
description: "Welcome! I'm Gemma, a PhD researcher working on historical sociolinguistics."
