menu:
#- {name: 'people', url: '/people'}
- {name: 'papers & talks', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

#courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
#- {icon: 'github', link: 'https://github.com/LeNPaul'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-0059-4457'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Gemma_Mccarley'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=MtE2unYAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gemma-mccarley-885a05269/'}

contacts:
- {name: 'Gemma McCarley', title: 'Postdoctoral Fellow', department: 'Linguistics', institution: 'University of Toronto', institution_address: 'Sidney Smith Hall | 100 St. George St. | Toronto, ON | M5S 3G3', email: 'gemma.mccarley@utoronto.ca', office: '6027B', image: 'assets/img/UoT logo.png'}
